# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82f0fedafc6071397166ddcc99f5a9ca59b58568ebc5c0188c27f359294216a52b7a37564f2c1c3eeff6c207c5ec291bbbb2dde531d65235d0217429e7c74ddc

test:
  secret_key_base: 92f9d4dc2eae9cb1797da962e93ce333f6c581277eccae48a9657e67e1e737b85c4c9e7a58b6302e59a81f5bec45b364325f508d105d6ae9d3d91ed3968c39d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
