development: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch('PGHOST', 'localhost') %>
  port: <%= ENV.fetch('PGPORT', 5432) %>
  username: <%= ENV.fetch('PGUSER', ENV.fetch('USER', 'postgres')) %>
  password: <%= ENV.fetch('PGPASSWORD', '') %>
  database: <%= ENV.fetch('STRADIVARI_TEST_DB', 'stradivari_test') %>

test:
  <<: *default
